name: Build Develop/Master

on:   [pull_request]

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{GITHUB_REPOSITORY }}:${{ github.event.pull_request.number }}

      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
